package geekdos;


/**
* geekdos/etudiantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionNotes.idl
* Thursday, January 5, 2017 10:44:12 AM WET
*/

public final class etudiantsHolder implements org.omg.CORBA.portable.Streamable
{
  public geekdos.Etudiant value[] = null;

  public etudiantsHolder ()
  {
  }

  public etudiantsHolder (geekdos.Etudiant[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = geekdos.etudiantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    geekdos.etudiantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return geekdos.etudiantsHelper.type ();
  }

}
