package geekdos;

/**
* geekdos/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionNotes.idl
* Thursday, January 5, 2017 10:44:12 AM WET
*/

public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public geekdos.Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (geekdos.Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = geekdos.EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    geekdos.EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return geekdos.EtudiantHelper.type ();
  }

}
