package geekdos;


/**
* geekdos/GestionNotesInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionNotes.idl
* Thursday, January 5, 2017 10:44:12 AM WET
*/

public interface GestionNotesInterface extends GestionNotesInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotesInterface
