package geekdos;


/**
* geekdos/GestionNotesInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionNotes.idl
* Thursday, January 5, 2017 10:44:12 AM WET
*/

public abstract class GestionNotesInterfacePOA extends org.omg.PortableServer.Servant
 implements geekdos.GestionNotesInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouterEtudiant", new java.lang.Integer (0));
    _methods.put ("getNote", new java.lang.Integer (1));
    _methods.put ("getEtudiantsTries", new java.lang.Integer (2));
    _methods.put ("getValidant", new java.lang.Integer (3));
    _methods.put ("getMajorant", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // geekdos/GestionNotesInterface/ajouterEtudiant
       {
         geekdos.Etudiant e = geekdos.EtudiantHelper.read (in);
         this.ajouterEtudiant (e);
         out = $rh.createReply();
         break;
       }

       case 1:  // geekdos/GestionNotesInterface/getNote
       {
         String cne = in.read_string ();
         float $result = (float)0;
         $result = this.getNote (cne);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // geekdos/GestionNotesInterface/getEtudiantsTries
       {
         geekdos.Etudiant $result[] = null;
         $result = this.getEtudiantsTries ();
         out = $rh.createReply();
         geekdos.etudiantsHelper.write (out, $result);
         break;
       }

       case 3:  // geekdos/GestionNotesInterface/getValidant
       {
         geekdos.Etudiant $result[] = null;
         $result = this.getValidant ();
         out = $rh.createReply();
         geekdos.etudiantsHelper.write (out, $result);
         break;
       }

       case 4:  // geekdos/GestionNotesInterface/getMajorant
       {
         geekdos.Etudiant $result = null;
         $result = this.getMajorant ();
         out = $rh.createReply();
         geekdos.EtudiantHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:geekdos/GestionNotesInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionNotesInterface _this() 
  {
    return GestionNotesInterfaceHelper.narrow(
    super._this_object());
  }

  public GestionNotesInterface _this(org.omg.CORBA.ORB orb) 
  {
    return GestionNotesInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class GestionNotesInterfacePOA
