
package com.geekdos.client;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Halima", targetNamespace = "http://service.geekdos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Halima {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "sayChirira", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.SayChirira")
    @ResponseWrapper(localName = "sayChiriraResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.SayChiriraResponse")
    @Action(input = "http://service.geekdos.com/Halima/sayChiriraRequest", output = "http://service.geekdos.com/Halima/sayChiriraResponse")
    public void sayChirira();

}
