
package com.geekdos.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HalimaService", targetNamespace = "http://service.geekdos.com/", wsdlLocation = "http://localhost:8088/SeyHello?wsdl")
public class HalimaService
    extends Service
{

    private final static URL HALIMASERVICE_WSDL_LOCATION;
    private final static WebServiceException HALIMASERVICE_EXCEPTION;
    private final static QName HALIMASERVICE_QNAME = new QName("http://service.geekdos.com/", "HalimaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/SeyHello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HALIMASERVICE_WSDL_LOCATION = url;
        HALIMASERVICE_EXCEPTION = e;
    }

    public HalimaService() {
        super(__getWsdlLocation(), HALIMASERVICE_QNAME);
    }

    public HalimaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HALIMASERVICE_QNAME, features);
    }

    public HalimaService(URL wsdlLocation) {
        super(wsdlLocation, HALIMASERVICE_QNAME);
    }

    public HalimaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HALIMASERVICE_QNAME, features);
    }

    public HalimaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HalimaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Halima
     */
    @WebEndpoint(name = "HalimaPort")
    public Halima getHalimaPort() {
        return super.getPort(new QName("http://service.geekdos.com/", "HalimaPort"), Halima.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Halima
     */
    @WebEndpoint(name = "HalimaPort")
    public Halima getHalimaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.geekdos.com/", "HalimaPort"), Halima.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HALIMASERVICE_EXCEPTION!= null) {
            throw HALIMASERVICE_EXCEPTION;
        }
        return HALIMASERVICE_WSDL_LOCATION;
    }

}
