package msg;

/**
* msg/DateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionMsgElectronique.idl
* Thursday, January 12, 2017 11:34:32 AM WET
*/

public final class DateHolder implements org.omg.CORBA.portable.Streamable
{
  public msg.Date value = null;

  public DateHolder ()
  {
  }

  public DateHolder (msg.Date initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = msg.DateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    msg.DateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return msg.DateHelper.type ();
  }

}
