package msg;


/**
* msg/Date.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionMsgElectronique.idl
* Thursday, January 12, 2017 11:34:32 AM WET
*/

public final class Date implements org.omg.CORBA.portable.IDLEntity
{
  public int year = (int)0;
  public int month = (int)0;
  public int day = (int)0;
  public int hour = (int)0;
  public int min = (int)0;
  public int sec = (int)0;

  public Date ()
  {
  } // ctor

  public Date (int _year, int _month, int _day, int _hour, int _min, int _sec)
  {
    year = _year;
    month = _month;
    day = _day;
    hour = _hour;
    min = _min;
    sec = _sec;
  } // ctor

} // class Date
