package msg;

/**
* msg/MessengerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionMsgElectronique.idl
* Thursday, January 12, 2017 11:34:32 AM WET
*/

public final class MessengerHolder implements org.omg.CORBA.portable.Streamable
{
  public msg.Messenger value = null;

  public MessengerHolder ()
  {
  }

  public MessengerHolder (msg.Messenger initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = msg.MessengerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    msg.MessengerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return msg.MessengerHelper.type ();
  }

}
