package msg;


/**
* msg/MessengerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionMsgElectronique.idl
* Thursday, January 12, 2017 11:34:32 AM WET
*/

abstract public class MessengerHelper
{
  private static String  _id = "IDL:msg/Messenger:1.0";

  public static void insert (org.omg.CORBA.Any a, msg.Messenger that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static msg.Messenger extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (msg.MessengerHelper.id (), "Messenger");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static msg.Messenger read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MessengerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, msg.Messenger value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static msg.Messenger narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof msg.Messenger)
      return (msg.Messenger)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      msg._MessengerStub stub = new msg._MessengerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static msg.Messenger unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof msg.Messenger)
      return (msg.Messenger)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      msg._MessengerStub stub = new msg._MessengerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
