package msg;


/**
* msg/MessengerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionMsgElectronique.idl
* Thursday, January 12, 2017 11:34:32 AM WET
*/

public abstract class MessengerPOA extends org.omg.PortableServer.Servant
 implements msg.MessengerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("signup", new java.lang.Integer (0));
    _methods.put ("submit", new java.lang.Integer (1));
    _methods.put ("consult", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // msg/Messenger/signup
       {
         int $result = (int)0;
         $result = this.signup ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // msg/Messenger/submit
       {
         int id = msg._intHelper.read (in);
         msg.Message msg = msg.MessageHelper.read (in);
         this.submit (id, msg);
         out = $rh.createReply();
         break;
       }

       case 2:  // msg/Messenger/consult
       {
         int id = msg._intHelper.read (in);
         msg.Message $result = null;
         $result = this.consult (id);
         out = $rh.createReply();
         msg.MessageHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:msg/Messenger:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Messenger _this() 
  {
    return MessengerHelper.narrow(
    super._this_object());
  }

  public Messenger _this(org.omg.CORBA.ORB orb) 
  {
    return MessengerHelper.narrow(
    super._this_object(orb));
  }


} // class MessengerPOA
