package msg;


/**
* msg/MessengerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionMsgElectronique.idl
* Thursday, January 12, 2017 11:34:32 AM WET
*/

public interface MessengerOperations 
{
  int signup ();
  void submit (int id, msg.Message msg);
  msg.Message consult (int id);
} // interface MessengerOperations
