package msg;

/**
* msg/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionMsgElectronique.idl
* Thursday, January 12, 2017 11:34:32 AM WET
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public msg.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (msg.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = msg.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    msg.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return msg.MessageHelper.type ();
  }

}
