package Converter.dev;

/**
* EuroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* jeudi 29 d�cembre 2016 10 h 52 WET
*/

public interface EuroOperations 
{
  String Devise ();
  void Devise (String newDevise);
  float Taux ();
  void Taux (float newTaux);
  float toEuro (float devise);
  float toDevise (float euro);
} // interface EuroOperations
