package Converter.dev;

/**
* Euro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* jeudi 29 d�cembre 2016 10 h 52 WET
*/

public interface Euro extends EuroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Euro
