/*
#	Java Les fondamentaux
#	A. Tasso
#	Jeu de cartes
#	Fichier  : Carte.java
*/

package POO;

import javax.swing.ImageIcon;
// La classe Carte hérite des compoortements du composant JPanel
public class Carte extends javax.swing.JPanel {

     // Définition des propriétés
     private int id;
     private String urlDos;
     private String urlFace;



    // Définition du constructeur
    // 1er parametre : vue de face de la carte
    // second paramétre : vue de dos de la carte
    // troisieme paramètre : id de la carte
    public Carte(String urlf, String urld, int ni) {
         // Affichage des composants créés en mode Design
         initComponents();
         // Initialisation des propriétés par les méthodes set
         setUrlDos(urld);
         setUrlFace(urlf);
         setId(ni);
         // Par défaut une carte affiche la vue de dos
         tournerVersDos();
    }
    // Initialisation de la photo associée au dos de la carte
    public void setUrlDos(String tmp){
        urlDos = tmp;
    }
    // Initialisation de la photo associée à la vue de face de la carte
    public void setUrlFace(String tmp){
        urlFace = tmp;
    }
     // Initialisation de l'id de la carte
    public void setId(int tmp){
        id=tmp;
    }
    // Pour récupérer l'id de la carte
    public int getId() {
        return id;
    }
    // Méthode métier qui affiche la photo associée à l'url passée paramètre
     public void affichePhoto(String tmp){
         ImageIcon icon = new ImageIcon(tmp);
         photoLbl.setIcon(icon);
     }
     // Affiche la carte vue de face
     public void tournerVersFace(){
         affichePhoto(urlFace);
     }
     // Affiche la carte vue de dos
     public void tournerVersDos(){
         affichePhoto(urlDos);
     }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(57, 91));
        setPreferredSize(new java.awt.Dimension(57, 91));

        photoLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        photoLbl.setMaximumSize(new java.awt.Dimension(57, 91));
        photoLbl.setMinimumSize(new java.awt.Dimension(57, 91));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(photoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(photoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Déclaration de variables créées par NetBeans par l'intermédiaire du mode Design
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel photoLbl;
    // End of variables declaration//GEN-END:variables

}
