/*
#	Java Les fondamentaux
#	A. Tasso
#	Jeu de cartes
#	Fichier  : Message.java
*/

package POO;

// La classe Message hérite des comportements du composant JDialog
public class Message extends javax.swing.JDialog {

    // Constructeur d'une boite de dialogue  si modal = true, la fenêtre s'ouvre
    // et l'appllicaton reste bloquée tant que la fenêtre reste ouverte
    public Message(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        // Positionner la fenêtre en 100 sur l'axe des X et 70 sur l'axe des Y en tenant compte de la position de la fenêtre parente
        setBounds(parent.getX()+100,parent.getY()+70, 200, 300);
        // Affichage des composants créés en mode Design
        initComponents();
        // Rendre visible la fenêtre
        setVisible(true);
        // Associer les boutons radio au groupe de boutons
        grpBtn.add(ouiBtn);
        grpBtn.add(nonBtn);
        // Par défaut l'option oui est sélectionnée
        ouiBtn.setSelected(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpBtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ouiBtn = new javax.swing.JRadioButton();
        nonBtn = new javax.swing.JRadioButton();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("  Rejouer ?  "));

        ouiBtn.setText("Oui");
        ouiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiBtnActionPerformed(evt);
            }
        });

        nonBtn.setText("Non");
        nonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonBtnActionPerformed(evt);
            }
        });

        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(okBtn))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ouiBtn)
                            .add(nonBtn))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(38, 38, 38)
                .add(ouiBtn)
                .add(26, 26, 26)
                .add(nonBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 62, Short.MAX_VALUE)
                .add(okBtn)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Revenir à la fenêtre principale où les cartes sont mélangées et retournées
    public boolean okValider(){
      return true;
    }
    // Si le bouton ouiBtn est sélectionné
    private void ouiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiBtnActionPerformed
        // Le drapeau choix vaut true
        choix = true;
    }//GEN-LAST:event_ouiBtnActionPerformed
    // Si le bouton nonBtn est sélectionné
    private void nonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonBtnActionPerformed
         // Le drapeau choix vaut false
        choix = false;
    }//GEN-LAST:event_nonBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // Si le drapeau choix est vrai
        if(choix){
            // Effacer la fenêtre
            dispose();
        } 
        else{ // Si me drapeau choix est faux
            // Quitter l'appllication
            System.exit(0);
        }

    }//GEN-LAST:event_okBtnActionPerformed

      /**
      * Fonction main appelée à la création de la fenêtre modale
      * Rend visible la fenêtre au sein de laquelle sont placés les composants créés en mode Design
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Message dialog = new Message(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
     // variables globales utilisées par classe Message
    private boolean choix = true;
    // Déclaration de variables créées par NetBeans par l'intermédiaire du mode Design
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nonBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.JRadioButton ouiBtn;
    // End of variables declaration//GEN-END:variables

}
