
package Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculeAproxPiService", targetNamespace = "http://Services/", wsdlLocation = "http://localhost:8088/caculpi?wsdl")
public class CalculeAproxPiService
    extends Service
{

    private final static URL CALCULEAPROXPISERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULEAPROXPISERVICE_EXCEPTION;
    private final static QName CALCULEAPROXPISERVICE_QNAME = new QName("http://Services/", "CalculeAproxPiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/caculpi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULEAPROXPISERVICE_WSDL_LOCATION = url;
        CALCULEAPROXPISERVICE_EXCEPTION = e;
    }

    public CalculeAproxPiService() {
        super(__getWsdlLocation(), CALCULEAPROXPISERVICE_QNAME);
    }

    public CalculeAproxPiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULEAPROXPISERVICE_QNAME, features);
    }

    public CalculeAproxPiService(URL wsdlLocation) {
        super(wsdlLocation, CALCULEAPROXPISERVICE_QNAME);
    }

    public CalculeAproxPiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULEAPROXPISERVICE_QNAME, features);
    }

    public CalculeAproxPiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculeAproxPiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculeAproxPi
     */
    @WebEndpoint(name = "CalculeAproxPiPort")
    public CalculeAproxPi getCalculeAproxPiPort() {
        return super.getPort(new QName("http://Services/", "CalculeAproxPiPort"), CalculeAproxPi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculeAproxPi
     */
    @WebEndpoint(name = "CalculeAproxPiPort")
    public CalculeAproxPi getCalculeAproxPiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services/", "CalculeAproxPiPort"), CalculeAproxPi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULEAPROXPISERVICE_EXCEPTION!= null) {
            throw CALCULEAPROXPISERVICE_EXCEPTION;
        }
        return CALCULEAPROXPISERVICE_WSDL_LOCATION;
    }

}
