
package Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculeAproxPi", targetNamespace = "http://Services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculeAproxPi {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculer", targetNamespace = "http://Services/", className = "Client.Calculer")
    @ResponseWrapper(localName = "calculerResponse", targetNamespace = "http://Services/", className = "Client.CalculerResponse")
    @Action(input = "http://Services/CalculeAproxPi/calculerRequest", output = "http://Services/CalculeAproxPi/calculerResponse")
    public double calculer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
