
package com.geekdos.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionDesNotes", targetNamespace = "http://service.geekdos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionDesNotes {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNote", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetNote")
    @ResponseWrapper(localName = "getNoteResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetNoteResponse")
    @Action(input = "http://service.geekdos.com/GestionDesNotes/getNoteRequest", output = "http://service.geekdos.com/GestionDesNotes/getNoteResponse")
    public double getNote(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterEtudiant", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.AjouterEtudiant")
    @ResponseWrapper(localName = "ajouterEtudiantResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.AjouterEtudiantResponse")
    @Action(input = "http://service.geekdos.com/GestionDesNotes/ajouterEtudiantRequest", output = "http://service.geekdos.com/GestionDesNotes/ajouterEtudiantResponse")
    public List<Object> ajouterEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.geekdos.client.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNonValidation", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetNonValidation")
    @ResponseWrapper(localName = "getNonValidationResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetNonValidationResponse")
    @Action(input = "http://service.geekdos.com/GestionDesNotes/getNonValidationRequest", output = "http://service.geekdos.com/GestionDesNotes/getNonValidationResponse")
    public List<Etudiant> getNonValidation();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "saveEtudiants", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.SaveEtudiants")
    @ResponseWrapper(localName = "saveEtudiantsResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.SaveEtudiantsResponse")
    @Action(input = "http://service.geekdos.com/GestionDesNotes/saveEtudiantsRequest", output = "http://service.geekdos.com/GestionDesNotes/saveEtudiantsResponse")
    public void saveEtudiants();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "getAllEtudiants", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetAllEtudiants")
    @ResponseWrapper(localName = "getAllEtudiantsResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetAllEtudiantsResponse")
    @Action(input = "http://service.geekdos.com/GestionDesNotes/getAllEtudiantsRequest", output = "http://service.geekdos.com/GestionDesNotes/getAllEtudiantsResponse")
    public void getAllEtudiants();

    /**
     * 
     * @return
     *     returns java.util.List<com.geekdos.client.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getvalidation", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.Getvalidation")
    @ResponseWrapper(localName = "getvalidationResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetvalidationResponse")
    @Action(input = "http://service.geekdos.com/GestionDesNotes/getvalidationRequest", output = "http://service.geekdos.com/GestionDesNotes/getvalidationResponse")
    public List<Etudiant> getvalidation();

    /**
     * 
     * @return
     *     returns java.util.List<com.geekdos.client.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRat", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetRat")
    @ResponseWrapper(localName = "getRatResponse", targetNamespace = "http://service.geekdos.com/", className = "com.geekdos.client.GetRatResponse")
    @Action(input = "http://service.geekdos.com/GestionDesNotes/getRatRequest", output = "http://service.geekdos.com/GestionDesNotes/getRatResponse")
    public List<Etudiant> getRat();

}
