/*
#	Java Les fondamentaux
#	A. Tasso
#	Carnet d'adresses
#	Fichier  : Infos.java
*/

package CarnetModele;

import javax.swing.ImageIcon;

// La classe Saisie hérite des comportements du composant JPanel
public class Infos extends javax.swing.JPanel {
     
    // Constructeur dont le paramètre est la chaines de caractères contenant toutes les infos
    // pour un contact dans l'ordre suivant : prenom, nom, url, numTel, numPort, courriel, rue, ville
    public Infos(String []  nl) {
         // Afficher les composants créés en mode Design
        initComponents();
        setVisible(true);
        // Le prenom est stocké dans la premiere case du tableau (nl[0])
        setPrenom( nl[0]);
        // Le nom est stocké dans la seconde case du tableau (nl[1])
        setNom( nl[1]);
        // La photo  est stockée dans la troisième case du tableau (nl[2])
        setPhoto( nl[2]);
        // Le numéro de téléphone est stocké dans la quatrième case du tableau (nl[3])
        setNumTel( nl[3]);
        // Le numéro du portable est stocké dans la cinquième case du tableau (nl[4])
        setNumPort( nl[4]);
        // L'adresse mail  est stockée dans la sixième case du tableau (nl[5])
        setCourriel( nl[5]);
        // La rue est stockée dans la septième case du tableau (nl[6])
        setRue( nl[6]);
        // La ville est stockée dans la huitieme case du tableau (nl[7])
        setVille( nl[7]);
    }
    // Définition des méthodes en set, les valeurs passées en paramètre
    // sont placées dans les zonee de texte appropriées
    public void setNom(String tmp){
        nomLbl.setText(tmp);
    }
    public void setPrenom(String tmp){
        prenomLbl.setText(tmp);
    }
    public void setPhoto(String tmp){
        ImageIcon iconPhoto = new ImageIcon(tmp);
        photoLbl.setIcon(iconPhoto);
    }
    public void setNumTel(String tmp){
        numDomicileLbl.setText(tmp);
    }
    public void setNumPort(String tmp){
        numPortableLbl.setText(tmp);
    }
    public void setCourriel(String tmp){
        adresseCourrielLbl.setText(tmp);
    }
    public void setRue(String tmp){
        rueLbl.setText(tmp);
    }
     public void setVille(String tmp){
         villeLbl.setText(tmp);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();
        prenomLbl = new javax.swing.JLabel();
        nomLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        telephoneLbl = new javax.swing.JLabel();
        domicileLbl = new javax.swing.JLabel();
        numDomicileLbl = new javax.swing.JLabel();
        portableLbl = new javax.swing.JLabel();
        numPortableLbl = new javax.swing.JLabel();
        courrielLbl = new javax.swing.JLabel();
        adresseCourrielLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        adresseLbl = new javax.swing.JLabel();
        rueLbl = new javax.swing.JLabel();
        villeLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(300, 500));
        setLayout(null);
        add(photoLbl);
        photoLbl.setBounds(30, 20, 120, 120);

        prenomLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        add(prenomLbl);
        prenomLbl.setBounds(160, 20, 110, 60);

        nomLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        add(nomLbl);
        nomLbl.setBounds(160, 76, 90, 40);
        add(jSeparator1);
        jSeparator1.setBounds(102, 140, 178, 10);

        telephoneLbl.setText("Téléphone ");
        add(telephoneLbl);
        telephoneLbl.setBounds(60, 170, 69, 16);

        domicileLbl.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        domicileLbl.setForeground(new java.awt.Color(100, 100, 100));
        domicileLbl.setText("domicile");
        add(domicileLbl);
        domicileLbl.setBounds(60, 200, 48, 15);

        numDomicileLbl.setText("                       ");
        add(numDomicileLbl);
        numDomicileLbl.setBounds(130, 200, 120, 16);

        portableLbl.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        portableLbl.setForeground(new java.awt.Color(100, 100, 100));
        portableLbl.setText("portable");
        add(portableLbl);
        portableLbl.setBounds(60, 220, 60, 15);

        numPortableLbl.setText("                           ");
        add(numPortableLbl);
        numPortableLbl.setBounds(130, 220, 140, 16);

        courrielLbl.setText("Courriel");
        add(courrielLbl);
        courrielLbl.setBounds(60, 270, 50, 16);

        adresseCourrielLbl.setText("                                     ");
        add(adresseCourrielLbl);
        adresseCourrielLbl.setBounds(130, 270, 150, 16);
        add(jSeparator2);
        jSeparator2.setBounds(102, 325, 178, 10);

        adresseLbl.setText("Adresse");
        add(adresseLbl);
        adresseLbl.setBounds(60, 350, 50, 16);

        rueLbl.setText("                                             ");
        add(rueLbl);
        rueLbl.setBounds(130, 370, 200, 16);

        villeLbl.setText("                                                  ");
        add(villeLbl);
        villeLbl.setBounds(130, 400, 210, 16);
    }// </editor-fold>//GEN-END:initComponents

    // Déclaration de variables créées par NetBeans par l'intermédiaire du mode Design
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresseCourrielLbl;
    private javax.swing.JLabel adresseLbl;
    private javax.swing.JLabel courrielLbl;
    private javax.swing.JLabel domicileLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nomLbl;
    private javax.swing.JLabel numDomicileLbl;
    private javax.swing.JLabel numPortableLbl;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JLabel portableLbl;
    private javax.swing.JLabel prenomLbl;
    private javax.swing.JLabel rueLbl;
    private javax.swing.JLabel telephoneLbl;
    private javax.swing.JLabel villeLbl;
    // End of variables declaration//GEN-END:variables

}
